### ISSUE TITLE
disable asyncnet mode for Python 3.3

### ISSUE THREAD

**Issue by reverbc** [reverbc/pytest-concurrent#19]
From `gevent` pypi page:
> gevent runs on Python >= 2.7, Python >= 3.4

Should do a Python version check when selecting modes and throw some kind of exception to warn user it's not supported.

**Comment by hugovk** [comment]
Also Python 3.3 is now EOL, so you could just drop it: https://en.wikipedia.org/wiki/CPython#Version_history
