### ISSUE TITLE
asyncnet mode not handle output correctly

### ISSUE THREAD

**Issue by Xuanwo** [reverbc/pytest-concurrent#26]
While I print in a test fucntion, I expected them to be captrued, show up while the test failed and ignored while successful as mentioned in py.test docs: https://docs.pytest.org/en/latest/capture.html#using-print-statements-for-debugging

But asyncnet mode always print them to stdout.

**Comment by reverbc** [comment]
Hi @Xuanwo, could you share some example code to reproduce the issue?

**Comment by Xuanwo** [comment]
Closed for can't stable reproduction.
